### ISSUE TITLE
Epic: NSwag v13

### ISSUE THREAD

**Issue by RicoSuter** [RicoSuter/NSwag#1700]
**Topic: Remove deprecated apis**

Next: v14 https://github.com/RicoSuter/NSwag/issues/2181

Tasks/epics: 

- [x] Rename everything from Swagger to OpenApi? 
    - [x] Also rename JsonSchema4 to JsonSchema?
- [x] Upgrade to NJsonSchema v10
    - Move NSwag default settings to NJS (see SwaggerToCSharpGeneratorSettings.cs)
    - https://github.com/RicoSuter/NJsonSchema/pull/806
- [x] Change default setting of DefaultResponseReferenceTypeNullHandling to NotNull?
    - https://github.com/RicoSuter/NSwag/pull/2215
- [x] Remove `document.ToJson(JsonSchemaType.OpenApi3)` => now obsolete

NSwag.AspNetCore

- [x] Remove GeneratorSettings from SwaggerSettings<T> (also T)
- [x] Enable IOptions support (see TODOs)
- [x] Remove NSwag.SwaggerGeneration.WebApi dependency
- [x] Rename property SwaggerRoute / SwaggerUiRoute to DocumentPath and UiPath? (already in v12)
- [ ] ~~Use* use settings directly instead of Action => discuss this?~~

TypeScript/CSharp:

- [x] Changed default exception name to ApiException (added TypeScript option, changed for CSharp)

**Comment by RicoSuter** [comment]
Change default setting of DefaultResponseReferenceTypeNullHandling to NotNull?

**Comment by RicoSuter** [comment]
See https://github.com/RicoSuter/NSwag/pull/2178

**Comment by RicoSuter** [comment]
**Changes:**

- Changed default exception name to ApiException (added TypeScript option, changed for CSharp)
