### ISSUE TITLE
Epic: NSwag v14

### ISSUE THREAD

**Issue by RicoSuter** [RicoSuter/NSwag#2181]
We are now working on NSwag v14 and NJsonSchema v11.

Breaking changes: 

- [x] Removed some deprecated methods/properties
- [ ] Drop classic ASP.NET and full/legacy .NET support (?)
- [ ] Remove option to load assemblies (only project loading supported) (?)

Tasks (not sure they'll get in)

- [ ] Multiple file output: https://github.com/RSuter/NSwag/issues/1398
- [ ] Extension settings via assembly loader: https://github.com/RSuter/NSwag/issues/924

**Comment by olenitsj** [comment]
@RicoSuter, 

Does this mean NSwag will not support asp .net framework(OWIN) from v14?

**Comment by RicoSuter** [comment]
@olenitsj yes, I think this is the plan - there was enough time to migrate to .NET Core - and this is a free, open source product. 
Probably there wont be many patches as it's too time consuming and anyway not paid.

**Comment by kapsiR** [comment]
>  If we can keep it in some form, we'll keep it.

Would be cool to have support for the latest .NET Framework v4.8.* 😉

**Comment by Saibamen** [comment]
> there was enough time to migrate to .NET Core

We all know we don't like supporting legacy apps, frameworks SKDs etc... and (Hello) World will be a better place for us if all Customers will use latest versions, so we could use latest solutions etc... but...

There are still big projects with active development not yet migrated to .NET Core/.NET 6 LTS or in the middle of migration - so we need Swagger support for both WebAPIs to compare these.

And because of active development, developers can't have enough time to working ONLY on migrating and testing new APIs - especially on small companies.

**Comment by patrickklaeren** [comment]
> > there was enough time to migrate to .NET Core
> 
> We all know we don't like supporting legacy apps, frameworks, SKDs etc... and (Hello) World will be a better place for us if all Customers will use latest versions, so we could use latest solutions etc... but...
> 
> There are still big projects with active development not yet migrated to .NET Core/.NET 6 LTS or in the middle of migration - so we need Swagger support for both WebAPIs to compare these. A lot of changes were made in routing area for .NET Core.
> 
> And because of active development, developers can't have enough time to working ONLY on migrating and testing new APIs - especially on small companies.

Dropping support in new versions doesn't mean the version you're using at the moment will stop working :)
